name: Deploy to Render on Merge to Main

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Build and Deploy to Render
        run: |
          npm run build   # Run build if needed
          # Use Render's deployment mechanism, e.g., Render CLI or environment variables to trigger deployment
          curl -X POST "https://api.render.com/deployments" \
          -H "Authorization: Bearer ${{ secrets.RENDER_API_TOKEN }}" # Use Render's API token if necessary
